In [1]:
import numpy as np
import pandas as pd
import glob

In [2]:
filename_patient = './patientData/patientAS14.01.csv'

In [5]:
df_patient = pd.read_csv(filename_patient)
# Edit dataframe
df_patient['month'] = df_patient.apply(lambda row: row.time[5:7], axis=1)
df_patient['day'] = df_patient.apply(lambda row: row.time[8:10], axis=1)
df_patient['call'].fillna(0, inplace=True)
df_patient['sms'].fillna(0, inplace=True)
df_patient

,time,activity,circumplex.arousal,circumplex.valence,mood,appCat.builtin,appCat.communication,appCat.entertainment,appCat.finance,appCat.game,...,appCat.social,appCat.travel,appCat.unknown,appCat.utilities,appCat.weather,call,screen,sms,month,day
0,2014-02-26,NaN,-0.250000,0.750000,6.250000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,02,26
1,2014-02-27,NaN,0.000000,0.333333,6.333333,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,02,27
2,2014-03-20,0.081548,NaN,NaN,NaN,248.979,2168.229,350.856,NaN,NaN,...,807.731,NaN,45.173,21.074,NaN,1.0,2275.944000,0.0,03,20
3,2014-03-21,0.134050,0.200000,0.200000,6.200000,3139.218,6280.890,1007.456,49.544,NaN,...,4508.500,915.445,NaN,598.754,NaN,6.0,17978.907000,0.0,03,21
4,2014-03-22,0.236880,0.600000,0.500000,6.400000,731.429,4962.918,93.324,21.076,NaN,...,439.632,37.305,NaN,117.621,NaN,3.0,6142.161000,1.0,03,22
5,2014-03-23,0.142741,0.200000,0.800000,6.800000,1286.246,5237.319,94.346,43.403,NaN,...,900.839,NaN,NaN,30.086,30.386,0.0,6773.832001,0.0,03,23
6,2014-03-24,0.078961,0.800000,0.000000,6.000000,866.956,9270.629,976.971,34.106,NaN,...,3223.626,419.805,NaN,178.732,NaN,10.0,15047.351001,0.0,03,24
7,2014-03-25,0.098374,0.500000,0.500000,6.750000,1032.768,10276.751,68.206,43.054,NaN,...,1919.471,NaN,235.223,222.893,NaN,0.0,21475.354999,1.0,03,25
8,2014-03-26,0.101308,-0.200000,0.600000,6.600000,1167.497,8988.753,910.479,52.331,NaN,...,4592.059,NaN,NaN,33.365,NaN,0.0,16423.801000,0.0,03,26
9,2014-03-27,0.159511,0.200000,0.800000,7.000000,1229.327,6936.512,639.339,42.219,NaN,...,935.381,47.314,NaN,179.029,NaN,2.0,17442.149999,1.0,03,27
10,2014-03-28,0.095698,-0.600000,0.600000,6.400000,10062.595,866.833,1005.403,89.166,233.036,...,512.741,1133.009,NaN,301.717,NaN,5.0,4923.489000,0.0,03,28
11,2014-03-29,0.068203,0.200000,1.000000,8.000000,1952.630,2720.692,1627.429,NaN,NaN,...,472.888,52.435,NaN,600.637,NaN,4.0,8322.622000,1.0,03,29
12,2014-03-30,0.049093,-0.500000,0.750000,7.500000,414.365,1298.505,1535.677,NaN,NaN,...,167.685,NaN,66.477,38.296,NaN,0.0,4523.214001,0.0,03,30
13,2014-03-31,0.070505,0.000000,0.600000,7.400000,2961.405,5332.637,1758.920,41.255,51.176,...,1350.655,183.381,29.290,210.305,NaN,6.0,11836.834000,0.0,03,31
14,2014-04-01,0.118443,0.200000,0.000000,6.000000,1385.517,6095.526,1030.637,547.826,234.741,...,5040.067,1614.621,NaN,517.636,NaN,1.0,17173.906002,0.0,04,01
15,2014-04-02,0.101917,0.333333,0.666667,6.500000,3614.349,6920.156,1343.376,247.777,NaN,...,3428.792,NaN,NaN,341.371,NaN,4.0,21358.511000,0.0,04,02
16,2014-04-03,0.049238,-1.200000,0.000000,6.400000,2321.464,14438.082,1293.631,76.234,NaN,...,3154.241,19.082,NaN,182.772,NaN,4.0,21401.835001,0.0,04,03
17,2014-04-04,0.126689,0.200000,0.400000,6.200000,1957.829,5481.628,1545.227,NaN,NaN,...,2086.197,158.241,NaN,128.692,NaN,2.0,12379.411000,1.0,04,04
18,2014-04-05,0.119002,-0.400000,0.600000,6.800000,15159.190,1885.409,76.369,NaN,NaN,...,363.208,187.945,NaN,118.956,NaN,0.0,3340.431000,0.0,04,05
19,2014-04-06,0.064408,-0.750000,0.500000,6.500000,4548.662,3355.743,187.214,NaN,114.406,...,321.460,NaN,NaN,46.249,NaN,4.0,7467.322000,0.0,04,06
20,2014-04-07,0.050671,-0.666667,0.250000,6.500000,927.377,7355.015,447.121,46.128,NaN,...,1475.418,60.247,NaN,205.811,NaN,1.0,9846.381000,0.0,04,07
21,2014-04-08,0.075327,-0.400000,0.333333,6.600000,892.689,9477.553,3466.479,19.131,NaN,...,2655.121,NaN,NaN,36.143,NaN,1.0,15101.132002,0.0,04,08
22,2014-04-09,0.120384,-0.800000,1.000000,7.400000,1638.617,6177.076,940.770,NaN,NaN,...,2826.350,NaN,NaN,577.359,NaN,4.0,13558.289001,0.0,04,09
23,2014-04-10,0.078963,-0.400000,0.800000,7.400000,715.355,4881.411,1858.893,NaN,1.059,...,1174.717,NaN,NaN,377.687,NaN,7.0,9296.098999,0.0,04,10
24,2014-04-11,0.079986,-1.200000,0.800000,7.000000,3369.031,3336.592,1976.138,94.093,NaN,...,596.807,34.234,NaN,214.648,NaN,0.0,10526.846000,0.0,04,11
25,2014-04-12,0.072249,-0.750000,0.750000,7.250000,302.446,6595.083,2186.482,NaN,NaN,...,264.432,5.031,NaN,352.392,NaN,0.0,11750.809001,0.0,04,12
26,2014-04-13,0.014021,-1.250000,1.000000,8.000000,447.415,1096.795,249.392,82.413,NaN,...,34.502,NaN,NaN,NaN,NaN,0.0,2005.750999,0.0,04,13
27,2014-04-14,0.083887,-1.200000,0.600000,7.200000,961.581,6486.284,6265.556,89.323,NaN,...,2921.985,29.104,NaN,986.014,NaN,1.0,17985.447999,1.0,04,14
28,2014-04-15,0.090112,0.000000,0.800000,6.400000,1596.356,6224.231,944.522,13.043,NaN,...,4428.210,8.363,NaN,279.793,NaN,8.0,13585.222998,1.0,04,15
29,2014-04-16,0.116110,0.750000,0.500000,7.200000,923.613,5175.016,426.734,NaN,NaN,...,1912.852,NaN,NaN,223.587,NaN,0.0,12522.474999,1.0,04,16
30,2014-04-17,0.056918,-0.400000,0.600000,6.600000,552.201,11853.339,142.241,NaN,NaN,...,2107.146,NaN,NaN,49.718,NaN,2.0,15018.480001,0.0,04,17
31,2014-04-18,0.094033,-0.800000,0.800000,6.800000,1860.898,5341.657,774.354,119.163,NaN,...,1993.922,63.874,NaN,88.680,NaN,1.0,13490.729000,0.0,04,18
32,2014-04-19,0.099432,-0.200000,1.000000,7.800000,946.190,2728.260,469.274,95.629,29.084,...,396.672,128.890,NaN,305.796,NaN,1.0,13293.248001,0.0,04,19
33,2014-04-20,0.074816,-0.250000,0.750000,7.250000,897.086,4984.724,727.492,10.606,NaN,...,2237.742,NaN,NaN,121.035,NaN,2.0,8343.518000,2.0,04,20
34,2014-04-21,0.102041,-0.250000,1.000000,7.600000,3442.232,2004.347,74.880,33.266,NaN,...,428.972,68.278,NaN,210.882,NaN,2.0,3832.990999,0.0,04,21
35,2014-04-22,0.091930,0.200000,1.000000,7.400000,2212.954,11360.913,1101.017,38.453,NaN,...,1422.548,NaN,NaN,423.215,NaN,2.0,15490.269999,0.0,04,22
36,2014-04-23,0.045986,0.200000,1.000000,7.600000,1130.842,8928.472,347.427,18.051,NaN,...,526.598,NaN,NaN,246.944,NaN,1.0,14535.339999,0.0,04,23
37,2014-04-24,0.050903,-0.400000,1.000000,7.600000,1466.271,9692.133,4464.975,209.937,NaN,...,2688.536,51.184,NaN,716.197,NaN,1.0,22086.478000,0.0,04,24
38,2014-04-25,0.109061,-0.200000,0.800000,7.200000,817.613,7279.144,650.832,21.071,NaN,...,2227.694,63.316,NaN,347.974,NaN,2.0,13973.942000,1.0,04,25
39,2014-04-26,0.214249,-0.200000,1.000000,7.600000,864.519,2567.857,125.556,27.267,NaN,...,2368.377,470.773,3.148,315.763,NaN,3.0,15482.018999,4.0,04,26
40,2014-04-27,0.030479,0.000000,1.000000,7.500000,1291.314,2431.498,1510.221,NaN,NaN,...,27.470,NaN,NaN,60.338,NaN,0.0,5700.562000,0.0,04,27
41,2014-04-28,0.019675,-0.800000,0.800000,7.600000,1312.001,4697.372,1548.438,465.253,NaN,...,2423.933,NaN,NaN,380.193,NaN,2.0,10807.830000,0.0,04,28
42,2014-04-29,0.102758,-0.250000,1.000000,7.000000,5289.913,3834.645,1562.533,NaN,333.305,...,411.485,41.982,NaN,410.436,NaN,0.0,7873.291999,0.0,04,29
43,2014-04-30,0.151051,-0.400000,0.750000,7.800000,844.963,3550.618,504.862,375.022,NaN,...,89.166,272.798,NaN,112.295,NaN,1.0,9175.604999,0.0,04,30
44,2014-05-01,0.037065,-0.400000,1.000000,8.000000,1876.113,8191.410,470.866,1321.104,NaN,...,4918.942,NaN,NaN,269.569,NaN,7.0,15516.951998,4.0,05,01
45,2014-05-02,0.077341,-0.200000,1.000000,7.600000,795.436,7925.918,352.888,1069.748,NaN,...,771.266,NaN,NaN,11.083,NaN,0.0,15088.519001,0.0,05,02
46,2014-05-03,0.071741,-0.200000,1.000000,8.000000,753.257,4539.776,2761.950,296.313,NaN,...,205.602,143.631,30.102,125.605,NaN,0.0,8186.036001,1.0,05,03
47,2014-05-04,0.136192,-0.500000,1.000000,8.000000,1758.438,3381.689,928.406,NaN,NaN,...,494.677,NaN,NaN,NaN,NaN,0.0,5889.194999,0.0,05,04
48,2014-05-05,0.007843,NaN,NaN,NaN,438.347,826.787,318.514,NaN,NaN,...,25.104,NaN,NaN,264.331,NaN,0.0,1788.734000,0.0,05,05

In [18]:
day = -1
row = df_patient.iloc[5]
int(row['day'])

23